app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("tasty.urls")),
]

app/tasty/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('recipe/catalogue/', views.recipe_catalogue, name='recipe_catalogue'),
    path('recipe/create/', views.recipe_create, name='recipe_create'),
    path('recipe/<int:recipe_id>/details/', views.recipe_details, name='recipe_details'),
    path('recipe/<int:recipe_id>/edit/', views.recipe_edit, name='recipe_edit'),
    path('recipe/<int:recipe_id>/delete/', views.recipe_delete, name='recipe_delete'),
    path('profile/create/', views.profile_create, name='profile_create'),
    path('profile/details/', views.profile_details, name='profile_details'),
    path('profile/edit/', views.profile_edit, name='profile_edit'),
    path('profile/delete/', views.profile_delete, name='profile_delete'),
]

app/tasty/models.py
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator, MinValueValidator
from django.db import models

def validate_capital_letter(value):
    if not value[0].isupper():
        raise ValidationError("Name must start with a capital letter!")

class Profile(models.Model):
    nickname = models.CharField(
        max_length=20, unique=True, blank=False,
        validators=[MinLengthValidator(2, message="Nickname must be at least 2 chars long!")]
    )
    first_name = models.CharField(
        max_length=30, blank=False, validators=[validate_capital_letter]
    )
    last_name = models.CharField(
        max_length=30, blank=False, validators=[validate_capital_letter]
    )
    chef = models.BooleanField(default=False)
    bio = models.TextField(blank=True)

    def __str__(self):
        return self.nickname

class Recipe(models.Model):


    title = models.CharField(
        max_length=100, unique=True, blank=False,
        validators=[MinLengthValidator(10, message="Title must be at least 10 chars long!")]
    )
    CUISINE_CHOICES = [
        ('French', 'French'),
        ('Chinese', 'Chinese'),
        ('Italian', 'Italian'),
        ('Balkan', 'Balkan'),
        ('Other', 'Other'),
    ]
    cuisine_type = models.CharField(
        max_length=7, choices=CUISINE_CHOICES, blank=False
    )
    ingredients = models.TextField(
        blank=False,
        help_text="Ingredients must be separated by a comma and space."
    )
    instructions = models.TextField(blank=False)
    
    cooking_time = models.PositiveIntegerField(
        blank=False,
        validators=[MinValueValidator(1, message="Time cannot be below 1.")],
        help_text="Provide the cooking time in minutes."
    )
    image_url = models.URLField(blank=True)

    def __str__(self):
        return self.title

app/tasty/forms.py
from django.forms import ModelForm
from django import forms
from .models import Profile, Recipe

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['nickname', 'first_name', 'last_name', 'chef']


class ProfileFormEdit(ModelForm):
    class Meta:
        model = Profile
        fields = "__all__"


class RecipeForm(ModelForm):
    class Meta:
        model = Recipe
        fields = ['title', 'cuisine_type', 'ingredients', 'instructions', 'cooking_time', 'image_url']
        widgets = {
            'cuisine_type': forms.Select(),
            'ingredients': forms.Textarea(attrs={
                'placeholder': 'ingredient1, ingredient2, ...',
                'help_text': 'Ingredients must be separated by a comma and space.'
            }),
            'instructions': forms.Textarea(attrs={
                'placeholder': 'Enter detailed instructions here...'
            }),
            'image_url': forms.URLInput(attrs={
                'placeholder': 'Optional image URL here...'
            }),
            'cooking_time': forms.NumberInput(attrs={
                'help_text': 'Provide the cooking time in minutes.'
            })
        }

app/tasty/views.py
from django.shortcuts import render, redirect
from .models import Profile, Recipe
from .forms import ProfileForm, RecipeForm, ProfileFormEdit
from .utils import get_recipe_by_id, get_first_profile, get_all_recipe

def home(request):
     profile = get_first_profile()

     return render(request, 'home-page.html', {"profile": profile})

def recipe_catalogue(request):
    recipe = get_all_recipe()
    profile = get_first_profile()

    return render(request,'catalogue.html', {'recipe': recipe, "profile": profile})

def recipe_create(request):
    profile = get_first_profile()
    if request.method == 'POST':
        form = RecipeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('recipe_catalogue')  
        else:
            print("Form is not valid")
            print(form.errors)
    else:
        form = RecipeForm()

    return render(request, 'create-recipe.html', {'form': form, 'profile':profile})

def recipe_details(request,recipe_id):
    profile = get_first_profile()
    recipe = get_recipe_by_id(recipe_id)



    ingredients = recipe.ingredients.split(',')
    

    return render(request, 'details-recipe.html', {'recipe': recipe, 'profile':profile, 'ingredients': ingredients})

def recipe_edit(request,recipe_id):
    profile = get_first_profile()
    recipe = get_recipe_by_id(recipe_id)

    if request.method == 'POST':
        form = RecipeForm(request.POST,instance=recipe)
        if form.is_valid():
            
            form.save()
            
            return redirect('recipe_catalogue')  
        else:
            print("Form is not valid")
            print(form.errors)
    else:
       
        form = RecipeForm(instance=recipe)


    return render(request, 'edit-recipe.html', {'form': form, 'profile':profile})

def recipe_delete(request,recipe_id):
    profile = get_first_profile()
    recipe = get_recipe_by_id(recipe_id)

    if request.method == 'POST':
        recipe.delete()
        return redirect('recipe_catalogue')
    else:
        form = RecipeForm(instance=recipe)

    return render(request, 'delete-recipe.html', {'form': form, 'profile':profile})

def profile_create(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        if form.is_valid():
            form.save()  
            print("Profile created")
            return redirect('recipe_catalogue')  
        else:
            print("Form is not valid")
            print(form.errors)
    else:
        form = ProfileForm()

    return render(request, 'create-profile.html', {'form': form})

def profile_details(request):
    profile = get_first_profile()
    recipe_count = get_all_recipe().count()
    


    return render(request, 'details-profile.html', {'profile': profile,'recipe_count': recipe_count})

def profile_edit(request):
    profile = get_first_profile()
    
    if request.method == 'POST':
        form = ProfileFormEdit(request.POST,instance=profile)
        if form.is_valid():
            form.save()  
            
            return redirect('profile_details')  
        else:
            print("Form is not valid")
            print(form.errors)
    else:
        form = ProfileFormEdit(instance=profile)


    return render(request, 'edit-profile.html', {'form': form,'profile': profile})

def profile_delete(request):
    profile = get_first_profile()
    recipe = get_all_recipe()

    if request.method == 'POST':
        profile.delete()
        recipe.delete()
        return redirect('home')
    return render(request, 'delete-profile.html', {'profile': profile})

app/tasty/templates/base.html
{% load static %}



<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="/static/style/style.css" />
    <title>TastyRecipesApp</title>
  </head>


    <div id="box">
      <header>
        <!-- Navigation Bar -->
        <h1><a class="index-navigation" href="{% url 'home' %}">Tasty Recipes</a></h1>
        <nav>
            {% if not profile %}
          <!-- if the user has not created a profile -->
          <a href="{% url 'profile_create' %}">Create Profile</a>
          {% else %}
          <!-- if the user has created a profile -->
          <a href="{% url 'recipe_catalogue' %}">Catalogue</a>
          <a href="{% url 'recipe_create' %}">Create Recipe</a>
          <a href="{% url 'profile_details' %}">Profile</a>
          {% endif %}
        </nav>
      </header>

    </div>
</body>
</html>


      {% block content %}


      {% endblock content %}
  
      {% block footer %}
      <footer>&copy;SoftUni Team 2024. All rights reserved.</footer>
      {% endblock footer %}

app/tasty/templates/catalogue.html
{% extends 'base.html' %}

{% block content %}
      {% if not recipe %}
      <!-- Display paragraph: If there are no recipes yet-->
      <p class="no-articles">There are currently no recipes available.</p>
      {% else %}
      <!-- Display a card with information about each recipe (if any)-->
      <section id="catalogue">
        <!-- first recipe-->
        {% for recipes in recipe %}
        <div class="recipe-card">
          <div class="image-wrap">
            {% if recipes.image_url%}
            <img
            class="recipe-img"
            src="{{ recipes.image_url }}"
            alt="recipe image"
          />
            <!-- recipe image -->
            <!-- if there is no image url provided, display the default recipe image -->
            {% else %}
            <img
            class="recipe-img"
            src="/static/images/default_recipe_img.png"
            alt="recipe image"
          />
            {% endif %}
          </div>
          <!-- recipe title -->
          <h3>{{recipes.title}}</h3>
          <!-- recipe cooking time -->
          <h1>Cooking time: {{recipes.cooking_time}}.</h1>
          <!-- recipe instructions -->
          <h1>{{recipes.instructions|slice:":35"}}...</h1>
          <div class="details-buttons">
            <!-- recipe details button -->
            <a href="{% url 'recipe_details' recipes.id %}" class="details-btn">Details</a>
          </div>
        </div>

        {% endfor %}
      {% endif %}

      {% endblock content %}

app/tasty/templates/create-profile.html
{% extends 'base.html' %}

{% block content %}


      <!-- create profile form -->
      <section id="register-page" class="content auth">
        <form id="register" method="post">
          <div class="container">
            {% for field in form %}
            <div>

                {% if field.errors %}
                <ul class="errorlist">
                    <li>{{ field.label }}
                        <ul class="errorlist">
                            {% for error in field.errors %}
                            <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    </li>
                </ul>
                {% endif %}
            </div>
            {% endfor %}
            {% csrf_token %}
            <h1>Create Profile</h1>
            <div>
              <label for="id_nickname">Nickname:</label>

              {{form.nickname}}
            </div>

            <div>
              <label for="id_first_name">First Name:</label>

              {{form.first_name}}
            </div>

            <div>
              <label for="id_last_name">Last Name:</label>

              {{form.last_name}}
            </div>

            <div>
              <label for="id_chef">Chef: {{ form.chef }}</label>

              
            </div>
            <!-- create button -->
            <input class="btn submit" type="submit" value="Create Profile" />
          </div>
        </form>
      </section>


      {% endblock content %}

app/tasty/templates/create-recipe.html
{% extends 'base.html' %}

{% block content %}




      <!-- create recipe form -->
      <section id="create-page" class="auth">
        <form id="create" method="post">
          <div class="container">
            {% csrf_token %}
            <h1 class="form-create-headline">Create Recipe</h1>
      
            
            {% for field in form %}
            <div class="form-group">
              <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
              
              {% if field.errors %}
                <ul class="errorlist">
                  {% for error in field.errors %}
                    <li>{{ error }}</li>
                  {% endfor %}
                </ul>



                
              {% endif %}
              {% if field.help_text %}
                <div class="helptext">
                  {{ field.help_text }}
                </div>
              {% endif %}
            </div>
            {{ field }}
            {% endfor %}
      
            <!-- create button -->
            <input class="btn" type="submit" value="Create Recipe" />
          </div>
        </form>
      </section>
      {% endblock content %}

app/tasty/templates/delete-profile.html
{% extends 'base.html' %}

{% block content %}

      <section id="create-page" class="auth">
        <div class="container">
         
          <h1>Are you sure you want to delete your profile?</h1>
          <!-- Delete Profile Form -->
          <form id="delete" method="post">
            {% csrf_token %}

            <!-- Confirm Button -->
            <input class="btn submit" type="submit" value="Yes" />
          </form>
        </div>
        <!-- End Delete Profile Form -->
      </section>

      {% endblock content %}

app/tasty/templates/delete-recipe.html
{% extends 'base.html' %}

{% block content %}
      <!-- delete recipe form -->
      <section id="delete-page" class="auth">
        <form id="delete" method="post" disabled="disabled">
          {% csrf_token %}
          <fieldset disabled="disabled" style="border:none">
          <div class="container">
            <h1>Delete Recipe</h1>
            
            {% for field in form %}
            <div class="form-group">
              <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
              
              {% if field.errors %}
                <ul class="errorlist">
                  {% for error in field.errors %}
                    <li>{{ error }}</li>
                  {% endfor %}
                </ul>
              {% endif %}
              {% if field.help_text %}
                <div class="helptext">
                  {{ field.help_text }}
                </div>
              {% endif %}
            </div>
            {{ field }}
            {% endfor %}
          </fieldset>
          <!-- delete button -->
          <input class="btn submit" type="submit" value="Delete Recipe" />
        </div>
      </form>

      </section>

      {% endblock content %}

app/tasty/templates/details-profile.html
{% extends 'base.html' %}
{% load text_filters %}

{% block content %}

      <!-- profile details section -->
      <section id="recipe-details">
        <h1>Profile Details</h1>
        <div class="info-section">
          <div class="recipe-header">
            <!-- default profile image -->
            <!-- if the user is not a chef - a default image - no_chef_img.png -->
            {% if not profile.chef%}
            <img
            class="recipe-img"
            src="/static/images/no_chef_img.png"
            alt="profile-image"
          /> 
          {% else %}

            <!-- if the user is a chef - a default image - chef_img.png -->

            <img
              class="recipe-img"
              src="/static/images/chef_img.png"
              alt="profile-image"
            />
            {% endif %}

            <!-- profile full name -->
            <h1>{{profile.name}}</h1>

            <!-- profile nickname -->
            <p class="description">Nickname: {{profile.nickname}}</p>

            <!-- profile bio -->
            {% if profile.bio %}
            <p class="description">Bio: {{profile.bio|wrap_at_35|safe}}</p>
            <!-- if no profile bio - display 'N/A' -->
            {% else %}
            <p class="description">Bio: N/A</p>
            {% endif %}

            <!-- total number of published recipes -->
            <p class="description">Published recipes: {{recipe_count}}</p>

            <!-- Edit/Delete buttons -->
            <div class="buttons">
              <a href="{% url 'profile_edit' %}" class="edit-button">Edit</a>
              <a href="{% url 'profile_delete' %}" class="delete-button">Delete</a>
            </div>
          </div>
        </div>
      </section>

      {% endblock content %}

app/tasty/templates/details-recipe.html
{% extends 'base.html' %}
{% load text_filters %}

{% block content %}


      <!-- details section -->
      <section id="recipe-details">
        <h1>Recipe Details</h1>
        <div class="info-section">
          <div class="recipe-header">
            <!-- recipe image -->
            <!-- if there is no image url provided, display the default recipe image -->
            {% if recipe.image_url%}
            <img
            class="recipe-img"
            src="{{ recipe.image_url }}"
            alt="recipe image"
          />            
          {% else %}
          <img
          class="recipe-img"
          src="/static/images/default_recipe_img.png"
          alt="recipe image"
        />
          {% endif %}

            <!-- recipe title -->
            <h1>{{recipe.title}}</h1>
            <!-- recipe cuisine type -->
            <p><span class="description-recipe">Cuisine Type: {{recipe.cuisine_type}}</span></p>
            <!-- recipe cooking time -->
            <p><span class="description-recipe">Cooking Time: {{recipe.cooking_time}}.</span></p>
            <!-- recipe ingredients -->
            <div class="ingredients">
              <p><span class="description-recipe">Ingredients:</span></p>
              <ul>
                {% for ingredient in ingredients%}
                <!-- recipe ingredient -->
                <li>{{ingredient}}</li>
                {% endfor %}
              </ul>
            </div>
            <p>
              <span class="description-recipe"
                >Instructions: 
                 {{recipe.instructions|wrap_at_35|safe}}</span>
            </p>
          </div>

          <!-- Edit/Delete buttons -->
          <div class="buttons">
            <a href="{% url 'recipe_edit' recipe.id %}" class="edit-button">Edit</a>
            <a href="{% url 'recipe_delete' recipe.id %}" class="delete-button">Delete</a>
          </div>
        </div>
      </section>

      {% endblock content %}

app/tasty/templates/edit-profile.html
{% extends 'base.html' %}

{% block content %}

      <!-- edit profile form -->
      <section id="register-page" class="content auth">
        <form id="register" method="post">
          <div class="container">
            {% for field in form %}
            <div>

                {% if field.errors %}
                <ul class="errorlist">
                    <li>{{ field.label }}
                        <ul class="errorlist">
                            {% for error in field.errors %}
                            <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    </li>
                </ul>
                {% endif %}
            </div>
            {% endfor %}
            {% csrf_token %}
            <h1>Edit Profile</h1>
            <div>
              <label for="id_nickname">Nickname:</label>

              {{form.nickname}}
            </div>

            <div>
              <label for="id_first_name">First Name:</label>

              {{form.first_name}}
            </div>

            <div>
              <label for="id_last_name">Last Name:</label>

              {{form.last_name}}
            </div>

            <div>
              <label for="id_chef">Chef: {{ form.chef }}</label>
            </div>

            <div>
              <label for="id_bio">Bio:</label>

              {{form.bio}}
            </div>
            <!-- edit button -->
            <input class="btn" type="submit" value="Edit Profile" />
          </div>
        </form>
      </section>

      {% endblock content %}

app/tasty/templates/edit-recipe.html
{% extends 'base.html' %}

{% block content %}


      <!-- edit recipe form -->
      <section id="create-page" class="auth">
        <form id="create" method="post">
          <div class="container">
            <h1>Edit Recipe</h1>
            <div>
              {% csrf_token %}
              {% for field in form %}
              <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                
                {% if field.errors %}
                  <ul class="errorlist">
                    {% for error in field.errors %}
                      <li>{{ error }}</li>
                    {% endfor %}
                  </ul>
                {% endif %}
                {% if field.help_text %}
                  <div class="helptext">
                    {{ field.help_text }}
                  </div>
                {% endif %}
              </div>
              {{ field }}
              {% endfor %}
            <!-- edit button -->
            <input class="btn submit" type="submit" value="Edit Recipe" />
          </div>
        </form>
      </section>

      {% endblock content %}

app/tasty/templates/home-page.html
      {% extends 'base.html' %}

      {% block content %}

      <!-- headlines -->
      <section id="index-headline">
        <div class="index-message">
          <h2>Explore, Create, and Share</h2>
          <h3>Culinary Delights</h3>
          <h4>with TastyRecipes App!</h4>
        </div>
      </section>
      {% endblock content %}
      
    